name: direct_link
description: Flutter package for direct link extractor from URL to stream and download directly
version: 0.1.1
author: Thit Lwin <thitlwincoder@gmail.com>
homepage: https://github.com/thitlwincoder/Direct_Link

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  requests: ^3.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter