name: direct_link
description: Flutter package for direct link extractor from URL to stream and
  download directly.
version: 0.1.9
homepage: https://github.com/thitlwincoder/direct_link

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  html: ^0.15.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
