name: direct_link
description: Dart package for direct link extractor from URL to stream and download directly.
version: 0.2.1
homepage: https://github.com/thitlwincoder/direct_link

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  html: ^0.15.4
  puppeteer: ^3.4.1

dev_dependencies:
  test: ^1.24.7
  lints: ^2.1.1
