name: direct_link
description: Flutter package for direct link extractor from URL to stream and
  download directly.
version: 0.1.9
homepage: https://github.com/thitlwincoder/direct_link

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  html: ^0.15.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.1
